version: "2"

services:
  base:
    image: busybox
    command: "/bin/sh -c -- 'trap : INT TERM; sleep 999999d & wait || :'"
    extra_hosts:
      # services
      - "web:127.0.0.1"
      - "grpc-server:127.0.0.1"
      - "nginx:127.0.0.1"
      - "mitmdump:127.0.0.1"
      # hosts
      - "web.seekplum.top:127.0.0.1"
      - "grpc.seekplum.top:127.0.0.1"
    ports:
      # external -> proxy
      - 8080:8080
      - 8081:8088
      - 8082:80
    restart: on-failure

  python:
    image: mitm-grpc-python:test
    build:
      context: ..
      dockerfile: app/Dockerfile

  go:
    image: mitm-grpc-go:test
    build:
      context: ..
      dockerfile: go-client/Dockerfile

  web:
    extends: python
    network_mode: service:base

  grpc-server:
    extends: python
    network_mode: service:base
    command: python app/protos/hello_server.py

  python-client:
    extends: python
    network_mode: service:base
    command: python app/protos/hello_client.py
    environment:
      - CHANNEL_SERVER_TARGET=nginx:80
      - CHANNEL_SERVER_SECURE=tls
      - GRPC_VERBOSITY=error
      - GRPC_TRACE=tcp,http,api
    depends_on:
      - nginx

  go-client:
    extends: go
    network_mode: service:base
    environment:
      - CHANNEL_SERVER_TARGET=nginx:80
      - CHANNEL_SERVER_SECURE=tls
      - GODEBUG="x509ignoreCN=0"
      - GRPC_VERBOSITY=error
      - GRPC_TRACE=tcp,http,api
      # - HTTP_PROXY=127.0.0.1:8080
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    network_mode: service:base
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy_params:/etc/nginx/proxy_params
      - ./nginx/extras:/etc/nginx/extras
      - ../mygrpc/keys/key.pem:/etc/nginx/certs/key.pem
      - ../mygrpc/keys/cert.pem:/etc/nginx/certs/cert.pem
    depends_on:
      - web
      - grpc-server
    restart: on-failure

  mitmdump:
    image: mitmproxy/mitmproxy
    network_mode: service:base
    volumes:
      - ./proxy_rewrite.py:/home/mitmproxy/custom/proxy_rewrite.py
      - ../mygrpc/keys/cert.pem:/home/mitmproxy/custom/cert.pem
    working_dir: /home/mitmproxy
    command: >-
      mitmdump
      --listen-port 8080
      --scripts custom/proxy_rewrite.py
      --rawtcp
      --tcp-hosts .*
      --ssl-insecure
      --flow-detail 3
      --http2
      --set http2_priority=true
      --set client_certs=custom/cert.pem
    # --set relax_http_form_validation=true
    mem_limit: "192m"
    restart: on-failure
    depends_on:
      - nginx
